{"stats": {"errors": 1, "failures": 0, "passes": 0, "skipped": 0, "encoding": "UTF-8", "total": 1}, "results": [{"classname": "index_test:S256Test", "name": "test_verify", "time": 0.2976562976837158, "type": "error", "errtype": "builtins.AttributeError", "message": "'S256Field' object has no attribute 'sum'", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/CassandraLeigh/signing-and-verification-jsong-pb-sf-072618/test/index_test.py\", line 13, in test_verify\n    self.assertTrue(point.verify(z, Signature(r, s)))\n  File \"/home/CassandraLeigh/signing-and-verification-jsong-pb-sf-072618/index.ipynb\", line 81, in verify\n    \"     0x68342ceff8935ededd102dd876ffd6ba72d6a427a3edb13d26eb0781cb423c4),\\n\",\nAttributeError: 'S256Field' object has no attribute 'sum'\n"}]}